/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.0/samples
 */

plugins{
  id("java")
  id("application")
}

dependencies{
	implementation("com.h2database:h2:2.2.220")
}

repositories{
	mavenCentral()
}

application{
	mainClass = "hexlet.code.Application"
}